name: Run Tests

on:
  push:
    branches:
      - main  # Or specify any branch you want to run tests on push
  pull_request:
    branches:
      - main  # Run tests on PRs to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assumes your dependencies are in requirements.txt
          pip install pytest               # Installs pytest if not in requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings  # Run pytest with options
